import type { Camera } from '@/canvas/Camera';
import type { CanvasView } from '@/canvas/CanvasView';
import type { Artboard } from '@/canvas/system';
import type { ShapeManager } from '@/shapes/ShapeManager';
import type { SelectionState } from '@/canvas/overlays/selection/SelectionState';
import type { HitTestEngine } from '@/core/HitTestEngine';
import type { SelectionHandler } from '@/canvas/overlays/selection/handlers/SelectionHandler';
import type { SelectionManager } from '@/canvas/overlays/selection/SelectionManager';
import type { PathNodeOverlay } from '@/canvas/overlays/selection/PathNodeOverlay';
import type { TransformHandler } from '@/canvas/overlays/selection/transform/TransformHandler';
import type { GroupTransformHandler } from '@/canvas/overlays/selection/transform/GroupTransformHandler';
import type { GridOverlay } from '@/canvas/overlays/debug/GridOverlay';
import type { GroupManager } from '@/shapes/group';
import type { CommandBus } from '../CommandBus';
import type { TimeMachine } from '@/time-machine';
import type { GuidelineManager } from '@/canvas/system/ruler';
import type { Rulers } from '@/canvas/system';
import type { CreationHandler } from '@/commands/handlers/creation/CreationHandler';
import type { ExternalApi } from '@/api/external-api';
import type { EventBus } from '../EventBus';
import type { ElementManager } from './ElementManager';

export interface ICanvasContext {
  readonly svg: SVGSVGElement;
  readonly camera: Camera;
  readonly view: CanvasView;
  readonly artboard: Artboard;
  readonly shapeManager: ShapeManager;
  readonly selectionState: SelectionState;
  readonly hitTestEngine: HitTestEngine;
  readonly commandBus: CommandBus;
  readonly timeMachine: TimeMachine;
  readonly events: EventBus;
  readonly api: ExternalApi;
  readonly selectionManager: SelectionManager;
  readonly pathNodeOverlay: PathNodeOverlay;
  readonly nodeEdit: import('@/canvas/overlays/nodeedit/NodeEditCoordinator').NodeEditCoordinator;
  readonly measure: import('@/canvas/overlays/measure/MeasureCoordinator').MeasureCoordinator;
  readonly laserGroupManager: import('@/laser').LaserGroupManager;
  readonly laserSettings: import('@/laser').LaserSettings;
  readonly laserColorResolver: import('@/laser').LaserColorResolver;
  readonly transformHandler: TransformHandler;
  readonly groupTransformHandler: GroupTransformHandler;
  readonly gridOverlay: GridOverlay;
  readonly groupManager: GroupManager;
  readonly elementManager: ElementManager;
  readonly rulers: Rulers;
  readonly guidelineManager: GuidelineManager;
  readonly selectionHandler: SelectionHandler;
  readonly creationHandler: CreationHandler;
}
